name: sci_http_client
description: Tercen http client library
version: 1.4.12

environment:
  sdk: ^3.3.0

dependencies:
  uuid:
  http:
  web_socket_channel: ^2.4.4
  #  tson:
  #    path: ../../dtson
  tson:
    git:
      url: https://github.com/tercen/dtson
      ref: 1.4.1
  logging:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
