name: sci_tercen_model
description: Tercen model.
version: 1.7.1

environment:
  sdk: ^3.3.0

dependencies:
  path: ^1.8.0
  uuid:
  sci_base:
    path: ../sci_base

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
